apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: s2kjovqta-python 
  janus-idp.io/tekton: s2kjovqta-python
  backstage.io/kubernetes-id: s2kjovqta-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: s2kjovqta-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml